### ISSUE TITLE
Bug on Google search results page

### ISSUE THREAD

**Issue by roccadev** [benblack86/linkclump#48]
When opening the top links, it also opens the Google main page:
![bug](https://cloud.githubusercontent.com/assets/11795213/12351191/189ca446-bb7c-11e5-9ff6-2c6a7931e666.jpg)
Is there anything you can do about it? Thanks

**Comment by nickbarry** [comment]
The reason for this is that Google is using sprites. Here's the full image, which is in fact the shape and size of the red outline you're seeing:
![nav_logo242](https://cloud.githubusercontent.com/assets/8515899/13720057/76649e6c-e7b4-11e5-8d37-56669bb29786.png)

The extension targets any links (including linked images) that it overlaps, which includes the Google image, even though most of the image is invisible to the user.

It could be possible, though, to update the script so that it ignores the specific url of the google logo sprite: https://www.google.com/images/nav_logo242.png

**Comment by nickbarry** [comment]
Update: @roccadev, you can solve this problem by doing the following:

1. Go into the Options for the Linkclump extension
2. Edit the "Opened as New Tabs" action
3. Make sure the "filter links" option is set to "exclude links with words" (this is the default setting)
4. In the text box for words to be excluded, paste _nav_logo242.png_

This will prevent the extension from opening the linked Google sprite image.

**Comment by roccadev** [comment]
Thanks, this is a perfect workaround.

**Comment by benblack86** [comment]
@nickbarry thanks for investigating. Any ideas how the code can work out the correct size of the displayed image/clickable link?

**Comment by nickbarry** [comment]
@benblack86 I believe the extension _is_ working out the correct size of the full image - it's a large image, and most of it just isn't visible. 
![google logo sprite](https://cloud.githubusercontent.com/assets/8515899/13900422/f05d7cfc-edc2-11e5-9266-b79174c8a5ba.png)

If you mean how could the code detect if only part of an image is actually in view, I notice that the image has dimensions of 167 x 410, but the <a> tag it's sitting inside has 95 x 37 dimensions (defined in CSS), and has overflow:hidden. I haven't dived too deeply into your code, but I'd guess from the Google behavior that the code detects if an element is linked, and if so, pays attention to the dimensions of the linked element. If that's correct, you could write an exception - if the containing link element has overflow:hidden, then use that link's dimensions instead. Or, maybe just always use the link tag's dimensions?
