### ISSUE TITLE
Breaks Google Photos's multiple selection mechanism which requires holding down the shift key.

### ISSUE THREAD

**Issue by BlueDude12** [benblack86/linkclump#63]
Could you just not expose it on the photos page? Probably would never be necessary there anyway.

**Comment by benblack86** [comment]
It would be time consuming for me to exclude every web site that had a conflict. I'm not even sure, which google website you are talking about. However, you can block sites yourself by using the blacklist functionality on the options page.

chrome-extension://lfpjkncokllnfokkgpkobnkbkmelfefj/pages/options.html

![screen shot 2017-04-03 at 19 57 18](https://cloud.githubusercontent.com/assets/315836/24636397/f0e65520-18a7-11e7-8202-2e1847cc9cd2.png)

**Comment by digitaltoast** [comment]
Hi there; for example, it breaks Google Sheets and any other similar site that requires shift/ctrl to select multiple rows. Took me AGES to find that it was link-clump causing this. I've added google sites to the blacklist, but meantime, I think it would be a great #1 FAQ and warning to have. 
PS - thanks for a great extension!

**Comment by benblack86** [comment]
Here are two ideas:

+ Change the default key to something else, for example, use "z" instead of shift/ctrl. Therefore, there would be less of a chance of a conflict.
+ Show some message to indicate that linkclump is activated when the key is pressed. Therefore, making it less of a mystery.

**Comment by digitaltoast** [comment]
I think "change default key" would be better, but of course, that would break behaviour for current users.
A "message on keypress" might help, depending on what it was.
How about an update which changes default key, but also comes with a one-time splash screen/ new tab like some extension updates have, explaining that the key has been changed because default ctrl/shift interfered with multi-select, and also reminding people that sites can be over-ridden and defaults changed. Wouldn't require much coding change, and then people might learn a bit more about it too. Everyone's a winner!

**Comment by benblack86** [comment]
I wouldn't change the default for existing users, just new ones.

**Comment by benblack86** [comment]
Just published 2.8.0, which changes the default for new users on all platforms to "z" key + left mouse button. Will see how many people complain...

**Comment by benblack86** [comment]
Going to close and new users should not experience this problem using the new defaults.
