### ISSUE TITLE
Not working as of Chrome Beta 60.0.3112.24

### ISSUE THREAD

**Issue by DakuTree** [benblack86/linkclump#69]
Linkclump doesn't seem to be working in the recent Chrome Beta ([60.0.3112.24](https://chromium.googlesource.com/chromium/src/+log/59.0.3071.86..60.0.3112.24?pretty=fuller&n=10000)).
Tried using different keys from the default right click and they don't seem to work either.

**Comment by benblack86** [comment]
What OS?

**Comment by DakuTree** [comment]
Windows 7.

**Comment by benblack86** [comment]
Reported chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=732632

**Comment by thusgaard** [comment]
Got what looks like the same issue on :
Browser: Chrome Version 60.0.3112.24 (Official Build) beta (64-bit)
OS: Windows 10 Pro, 64-bit, Version 1703, OS Build: 15063.296

Setting up linkclump to work with the left mouse button instead of the right mouse button, does allow for selection of links to be opened.

**Comment by benblack86** [comment]
Linkclump 2.7.7 has been published with a fix and should be available within a few hours.

**Comment by DakuTree** [comment]
2.7.7 seems to fixed the issue. Thanks :+1:
