### ISSUE TITLE
Using only "Right Click".

### ISSUE THREAD

**Issue by drs22** [benblack86/linkclump#85]
Hi.

I've been using Linkclump for years, and before I only had to use Right-Click to highlight links. But, I had to reset my PC, and now, I can't select the option of only using Right-Click. Now, it's only giving me the option of using Right-Click AND another key (Ctrl, Shift, Alt, etc.).

Is there a way to change the setting to allow using only Right-Click?

Thanks!

**Comment by privaterepository** [comment]
Hi Benjamin,
I have the same problem too. Please bring back Right-Click Only without any other optional key.
Thank you for your great extension anyway! Good work!

**Comment by mochakaboom** [comment]
Same here, what's going on??

One one account, I'm able to use only ONE button (right, let, or middle) to drag over the link.  Now they're making me press and hold ANOTHER  key.  I don't want that.  

Please bring back the single button option or add an option to disable the second button =/.

Thank you, other than that change it's a perfect app

**Comment by lootstrum** [comment]
Me too! Used the Chrome Cleanup Tool which reset my extensions... when I re-enabled Linkclump and it asked me to add actions from scratch, it has to be a mouse + key?? 
I've been using this extension for years and it's fantastic, but please bring this back!

**Comment by TyreeHarris** [comment]
I use this Extension all the time but I'm no longer to just use Right click 
Please Fix/Bring this back

**Comment by benblack86** [comment]
Yes, this option was removed. The problem is that not using a key+mouse button means that some websites wouldn't work correctly. I could bring it back, but then you might run into this problem and get frustrated that things aren't working and not know why. I could bring it back, but display a warning on the options page. What do people think?

**Comment by drs22** [comment]
I like that idea.

Thanks Ben for looking into this! I truly love this add-on!

**Comment by TyreeHarris** [comment]
Absolutely, I'd gladly Trade having a few problems with a couple websites in order to get the old "Right click and drag only" Option back!
Call it me being lazy but I commonly use this all the time, even for single links, or to kinda highlight all of the important words. 
Now Everything is frustratingly much, much Slower

**Comment by benblack86** [comment]
Publishing new version now. Should be ready in an hour.

**Comment by mochakaboom** [comment]
Cool! Thanks for the quick reply back benblack86.  Yea, it would definitely be useful since we've grown accustom to the "Only need one button" drag for years :).

**Comment by privaterepository** [comment]
Thank you Ben! 👍
